version: '3.8'

services:

  # Servicio Web (Aplicaci√≥n Flask)
  web:
    build: . # Usa el Dockerfile en el directorio actual
    container_name: flask_backend
    restart: always
    ports:
      - "8080:5000"
    env_file:
      - .env

